### PR TITLE
Mm counts2counts design issue

### PR DESCRIPTION
**Pull request by MikeDMorgan**
Resolve issue #165

### CODE REVIEW

**Comment by AndreasHeger** [comment]
Error in test_import:
/ifs/devel/andreas/cgat/scripts/clusters2metrics.py ... FAIL
AssertionError: clusters2metrics scripts/modules - ImportError: No module named Timeseries

Merge delayed.

**Comment by MikeDMorgan** [comment]
import statement fixed with commit c5eead162801af9153bd1afba4f8088225d6ecee

**Comment by AndreasHeger** [comment]
Thanks. There are errors in counts2counts:

======================================================================
FAIL: tests/wig2wig.py/version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/apps/apps/python-2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/ifs/devel/andreas/cgat/tests/test_scripts.py", line 178, in check_script
    ok_(not fail, msg)
AssertionError: error in statement: /bin/bash -c 'gunzip < /ifs/devel/andreas/cgat/tests/counts2counts.py/counts_small.tsv.gz | python /ifs/devel/andreas/cgat/scripts/counts2counts.py  --design-tsv-file=/ifs/devel/andreas/cgat/tests/counts2counts.py/design2.tsv --method="spike" --spike-type="row" --spike-maximum=1 --spike-change-bin-width=100 --spike-initial-bin-width=10 --spike-change-bin-max=10000 --spike-initial-bin-max=10 --difference-method=relative --random-seed=1234567890 -v0 > /tmp/tmpl17iWC/stdout'; stderr=Traceback (most recent call last):
  File "/ifs/devel/andreas/cgat/scripts/counts2counts.py", line 531, in <module>
    sys.exit(main(sys.argv))
  File "/ifs/devel/andreas/cgat/scripts/counts2counts.py", line 512, in main
    options.max_spike, options.iterations)
  File "/ifs/devel/andreas/cgat/CGAT/Counts.py", line 315, in shuffleRows
    tracks_map[groups[0]]].apply(
IndexError: list index out of range


======================================================================
FAIL: tests/wig2wig.py/version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/apps/apps/python-2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/ifs/devel/andreas/cgat/tests/test_scripts.py", line 178, in check_script
    ok_(not fail, msg)
AssertionError: error in statement: /bin/bash -c 'gunzip < /ifs/devel/andreas/cgat/tests/counts2counts.py/counts_small.tsv.gz | python /ifs/devel/andreas/cgat/scripts/counts2counts.py  --design-tsv-file=/ifs/devel/andreas/cgat/tests/counts2counts.py/design2.tsv --method="spike" --spike-type="row" --spike-maximum=1 --spike-change-bin-width=1 --spike-initial-bin-width=10 --spike-change-bin-max=10 --spike-initial-bin-max=10 --random-seed=1234567890 -v0 > /tmp/tmpNRwCG8/stdout'; stderr=Traceback (most recent call last):
  File "/ifs/devel/andreas/cgat/scripts/counts2counts.py", line 531, in <module>
    sys.exit(main(sys.argv))
  File "/ifs/devel/andreas/cgat/scripts/counts2counts.py", line 512, in main
    options.max_spike, options.iterations)
  File "/ifs/devel/andreas/cgat/CGAT/Counts.py", line 315, in shuffleRows
    tracks_map[groups[0]]].apply(
IndexError: list index out of range

**Comment by TomSmithCGAT** [comment]
Counts2counts.py has been modified on branch TS-Counts2countsRewrite and is passing tests.
Branch MM-counts2counts_design_issue has therefore been merged into TS-Counts2countsRewrite.

**Pull request closed without merging**
