### PR TITLE
gff2gff.py - in contig_pattern use search instead of match (match

### PR DESCRIPTION
**Pull request by snsansom**
only hits patterns at beginning of strings)

### CODE REVIEW

**Comment by snsansom** [comment]
Code is identical to master except for the one match -> search substitution - I've no idea why Travis is failing.

**Comment by TomSmithCGAT** [comment]
Hi Steve,

I think this is due to the changes to pep8 (See Andreas's email to CGAT-MEMBERS yesterday). Andreas is currently working through the code to resolve new pep8 issues.

Tom

________________________________

**Comment by IanSudbery** [comment]
Hmmm… Use ex-members don’t get CGAT-MEMBERs. Perhaps we need a contributors
mailing list for the cgat code?



*From:* Tom Smith [mailto:notifications@github.com]
*Sent:* 13 February 2015 12:29
*To:* CGATOxford/cgat
*Subject:* Re: [cgat] gff2gff.py - in contig_pattern use search instead of
match (match (#137)



Hi Steve,

I think this is due to the changes to pep8 (See Andreas's email to
CGAT-MEMBERS yesterday). Andreas is currently working through the code to
resolve new pep8 issues.

Tom

________________________________

**Comment by sebastian-luna-valero** [comment]
Hi all,

We could use CGAT-IT-NEWS or just use the Git Hub issues to make this announcements.

Best regards,
Sebastian.

**Comment by AndreasHeger** [comment]
On 02/13/15 12:36, Sebastian Luna Valero wrote:
> Hi all,
>
> We could use CGAT-IT-NEWS or just use the Git Hub issues to make this
> announcements.
>
> Best regards,
> Sebastian.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CGATOxford/cgat/pull/137#issuecomment-74247401>.
>
Indeed I should. Apologies!

**Pull request closed without merging**
