### PR TITLE
fixing racing problem

### PR DESCRIPTION
**Pull request by logust79**
the IOTools.shadowFile made the _infile_ look newer than _outfile_, thus making pipeline vulnerable. This pull fixes this problem by touching again the _outfile_ after generating the _infile_ to make _outfile_ newer than _infile_.

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Would it be possible to see a reproducible example of the original problem?

**Comment by logust79** [comment]
The original shadowFile will 
1. `move infile outfile`
2. `touch infile`

This will create `infiles` that are newer than `outfiles`.
This is problematic since if you want to use the outfile for the next step (a separate pipeline run), Ruffus see the `outfile` is older than the `infile` from the previous step, and will run the previous step. since the `infile` has nothing, it will remove all the content in the `outfile`, and the following steps will have a file with 0 byte size.

A pseudo example:
`echo 'this is awesome' > file1`
<pre><code>
@transform('file1','file1','file2')
def func1(infile, outfile):    
    IOTools.shadowFile(infile, outfile)

@transform(func1, 'file2', 'file3')
def func2(infile, outfile):
    IOTools.shadowFile(infile, outfile)
</code></pre>

then I first run this:
`python mypipeline make -v5 func1 -p1`
result: 
`file1 = ''` `file2 = 'this is awesome'`

I then run this:
`python mypipeline make -v5 func2 -p1`
since file1 is _touched_ after file2 was generated, ruffus tries to run func1 first
result:
`file1 = file2 = file3 = ''`

**Comment by sebastian-luna-valero** [comment]
Thanks!

Before going ahead, is your branch up to date with master?

E.g. the installation script was updated with new dependencies and should fix your previous errors on travis:
https://travis-ci.org/CGATOxford/cgat/builds/129415098

**Comment by logust79** [comment]
Good point! I keep forgetting that I am old!

**Pull request merged**
