### PR TITLE
gtf2table - add --sample-probability to enable down-sampling when counti...

### PR DESCRIPTION
**Pull request by snsansom**
...ng from bam files

          - raise error if trying to utilise a multi-mapping-method and the NH tag is absent
          - raise error if trying to utilise a mutli-mapping-method when counting PE bams

### CODE REVIEW

**Comment by snsansom** [comment]
Andreas please review these changes - in addition to adding sub-sampling when counting reads (to avoid having to down-sample bam files), I have tightened up the multi-mapping-methods (i) raising an error if the NH tag is not present (I can find no documentation that states that its absence implies a uniquely mapping read) and (ii) raising an error if multi-mapping-method is applied to paired end counting as the existing implementation did not appear appropriate - see comment in code (happy to be corrected) to me.

**Comment by AndreasHeger** [comment]
Thanks. Checking for NH is good and well spotted the inconsistent handling of multi-mapping for PE reads.
Happy also with the barcodes.

Is the sampling necessary - why not simply adjust the total counts by drawing from an appropriate distribution? Calling the random number generator costs a lot of time.

**Comment by snsansom** [comment]
Thanks.

On the sampling I prefer this approach for it's empirical simplicity. I
think it is directly equivalent to randomly down-sampling a bam before
counting - the motivation was to save the space of creating multiple
down-sampled bam files.

The random.random() call is only made if sampling_probability != 1, so
shouldn't affects runtime if sampling_probability is not enabled. When
sampling is enabled, a lot of time will also be saved by skipping the
counting loop for reads discarded.

**Comment by AndreasHeger** [comment]
Hmm, I am not entirely convinced, but ok, we can add sampling.

However, I am picky as I want to keep this part of the code high-performing. Before merging I suggest to:

1. avoid testing against 1.0 but use a flag and check its truth value. A float value comparison can potentially be slower.
2. use the C stdlib random number and not python's - otherwise it will be very, very slow.

**Comment by AndreasHeger** [comment]
@snsansom, I have had a go at this. Please take a look.

Best wishes,
Andreas

**Pull request merged**
