### PR TITLE
new method rename-chr for gff2gff.py

### PR DESCRIPTION
**Pull request by kevinrue**
Equivalent to previous PR for gff2gff.

Please do not merge until unit tests are implemented.

@sebastian-luna-valero : I assume this is about adding more entries in `https://github.com/CGATOxford/cgat/blob/master/tests/gff2gff.py/tests.yaml` ?

### CODE REVIEW

**Comment by kevinrue** [comment]
Let's see if I guessed correctly, about those unit tests. Haven't played with this kind of YAML setup before.

**Comment by sebastian-luna-valero** [comment]
Thanks!

Let's wait and see what travis says.

Did you also add the `chip_peaks.bed` file to the folder?

**Comment by sebastian-luna-valero** [comment]
Sorry, just realised that the `chip_peaks.bed` is already there.

I think you need to use `%DIR%` for your `ucsc2ensemble.txt` input file to get the tests passing; i.e.:
```
options: --method=rename-chr --rename-chr-file=%DIR%/ucsc2ensembl.txt
```
rather than:
```
options: --method=rename-chr --rename-chr-file=ucsc2ensembl.txt
```

**Comment by kevinrue** [comment]
Oops. Didn't spot that one in the other examples. Funny how input/reference files don't need that. I can see why that would be, despite the confusion.

**Comment by kevinrue** [comment]
Tada!!
Thanks for the help @sebastian-luna-valero !

**Comment by sebastian-luna-valero** [comment]
Great!

Before merging, could you please update this branch with the latest master? I have added in a couple of more tests, and I would like to see if this branch is ok with that.

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Thanks, @kevinrue 

You got `pep8` errors. To reproduce the problem locally, just run: `nosetests -v tests/test_style.py`

You can then do: `pep8 CGAT/scripts/gff2gff.py` to find out where the error is.

Here is a table with the error codes explained:
https://pep8.readthedocs.io/en/1.4.6/intro.html#error-codes

Please let me know if you need further help.

Best regards,
Sebastian

**Comment by kevinrue** [comment]
Yep, I just saw that this morning. I know PEP8, but I didn't remember that
there was a command for that. I'll make sure to use it on develop directly
in PyCharm, in the future.
Stand by while I correct this :)

**Comment by sebastian-luna-valero** [comment]
No worries, no rush.

Just wanted to make sure that the failed tests were not stopping you ;)

**Comment by kevinrue** [comment]
Did you disable some of the PEP8 checks for the CI?
I spotted and fixed the rules that my new lines broke, but `pep8` also pointed out some existing lines that are >80 characters wide, e.g.:
* https://github.com/kevinrue/cgat/blob/master/CGAT/scripts/gff2gff.py#L164
* https://github.com/kevinrue/cgat/blob/master/CGAT/scripts/gff2gff.py#L828
I don't really know how to solve those as they are somewhat naturally long lines.

**Comment by sebastian-luna-valero** [comment]
Yes, some PEP checks are skipped:
https://github.com/CGATOxford/cgat/blob/master/tests/test_style.py#L32

That's why running `nosetests -v tests/test_style.py` should give you the same answer as the CI.

Best regards,
Sebastian

**Comment by kevinrue** [comment]
Seems to be ready to go 🎉

**Comment by sebastian-luna-valero** [comment]
Thanks again!

**Pull request merged**
