### PR TITLE
Ac subsetbam

### PR DESCRIPTION
**Pull request by Acribbs**
Added downsampling function for both paired end and single end. Andreas checked function before christmas and suggested that because of the way dictionaries are called in python 3 the testing for this cannot be performed on py3 because the dictionary order is random. Therefore, testing is only performed for downsampling in python 2. This is a short term workaround until we can think of a way to test properly in py3.

### CODE REVIEW

**Comment by AndreasHeger** [comment]
Thanks. Possible solution is to set PYTHONHASHSEED environment variable. Issue, if I recall, is setting the numpy random seed?

**Comment by Acribbs** [comment]
Hi @AndreasHeger or @sebastian-luna-valero , I think this may solve the problem for py3 tests. However I can't test it because since the way we call scripts now is chat bam2bam, and not python bam2bam.py, I can not pass the -R option to python. Is there a pay of passing this option to an EASY-INSTALL-ENTRY-SCRIPT?

**Comment by sebastian-luna-valero** [comment]
Thanks @Acribbs 

I have pushed minor amendments.

Before going deeper into solving your problem, have you had a look at this:
http://stackoverflow.com/questions/18955554/get-random-keyvalue-pairs-from-dictionary-in-python

It looks like Python's `random.sample()` function can do what you need:
https://docs.python.org/2/library/random.html#random.sample
https://docs.python.org/3/library/random.html#random.sample

Would you be happy to give it a go or do you want me to try?

**Comment by Acribbs** [comment]
Have implemented suggestions by @sebastian-luna-valero and the tests are now passing. Thanks for help.

**Pull request merged**
