### PR TITLE
Is field order sequence properties na

### PR DESCRIPTION
**Pull request by IanSudbery**
Fix for issue #182

### CODE REVIEW

**Comment by IanSudbery** [comment]
@sebastian-luna-valero is there any way that I can force a re-run of the tests on this so that I can merge it into master?

**Comment by IanSudbery** [comment]
@sebastian-luna-valero: Travis reports here that this branch is failing, but if you look in travis, all the individual tests report success. Any idea where this is still failing?

Ian

**Comment by sebastian-luna-valero** [comment]
@IanSudbery 

I am rerunning the tests but Travis is malfunctioning. I will keep an eye on it.

Please wait until this is fixed.

**Comment by sebastian-luna-valero** [comment]
If anyone is interested, Travis status can be monitored here:
https://www.traviscistatus.com/

**Comment by IanSudbery** [comment]
Can this now be merged?

**Pull request merged**
