### PR TITLE
Ts counts2counts rewrite

### PR DESCRIPTION
**Pull request by TomSmithCGAT**
Branch includes changes previously commited by Mike on branch MM-counts2counts_design_issue and merged in this branch

### CODE REVIEW

**Comment by AndreasHeger** [comment]
I currently get:

======================================================================
FAIL: tests/wig2wig.py/version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/apps/apps/python-2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/ifs/devel/andreas/cgat/tests/test_scripts.py", line 178, in check_script
    ok_(not fail, msg)
AssertionError: files /tmp/tmppkwjCb/stdout and tests/counts2counts.py/normed_million_counts.tsv are not the same
/bin/bash -c 'gunzip < /ifs/devel/andreas/cgat/tests/counts2counts.py/counts_small.tsv.gz | python /ifs/devel/andreas/cgat/scripts/counts2counts.py  --method=normalize --normalization-method=million-counts -v 0 > /tmp/tmppkwjCb/stdout'
md5: output=98c680e35384aed2583e1f8febf891b0 reference=fd829ea8837198bb3cf05f0b7a1044f7

======================================================================
FAIL: tests/wig2wig.py/version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/ifs/apps/apps/python-2.7.9/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/ifs/devel/andreas/cgat/tests/test_scripts.py", line 178, in check_script
    ok_(not fail, msg)
AssertionError: files /tmp/tmpG6WEb3/stdout and tests/counts2counts.py/normed_deseq_size_factors.tsv are not the same
/bin/bash -c 'gunzip < /ifs/devel/andreas/cgat/tests/counts2counts.py/counts_small.tsv.gz | python /ifs/devel/andreas/cgat/scripts/counts2counts.py  --method=normalize --normalization-method=deseq-size-factors -v 0 > /tmp/tmpG6WEb3/stdout'
md5: output=5f8c2b519309ec396f54f09676b8e75f reference=5ce593b804317479158011874472f192

Best wishes,
Andreas

**Comment by TomSmithCGAT** [comment]
Hi Andreas. These were the tests which you'd commented out that fail on Travis but are OK locally. I'd removed the comment so I could check them locally but forgot to comment them back out before pushing. I'll do that  now and re-push.

Tom

Dr Tom Smith
CGAT Training Fellow | http://www.cgat.org
MRC Functional Genomics Unit | University of Oxford
+44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk

________________________________________

**Comment by AndreasHeger** [comment]
Thanks. Interestingly they failed for me locally. Must be something that 
is different in your environment and mine that causes the method to
give different outputs. Might be a chance to fix this.

Can you please create outputs for the following statements and save them 
somewhere?

```/ifs/devel/andreas/cgat/tests/counts2counts.py/counts_small.tsv.gz |
python /ifs/devel/andreas/cgat/scripts/counts2counts.py
--method=normalize --normalization-method=million-counts -v 0 > a.out

/ifs/devel/andreas/cgat/tests/counts2counts.py/counts_small.tsv.gz |
python /ifs/devel/andreas/cgat/scripts/counts2counts.py
--method=normalize --normalization-method=deseq-size-factors -v 0 > b.out

Best wishes,
Andreas

On 04/09/15 15:07, Tom Smith wrote:
> Hi Andreas. These were the tests which you'd commented out that fail on
> Travis but are OK locally. I'd removed the comment so I could check them
> locally but forgot to comment them back out before pushing. I'll do that
> now and re-push.
>
> Tom
>
> Dr Tom Smith
> CGAT Training Fellow | http://www.cgat.org
> MRC Functional Genomics Unit | University of Oxford
> +44 1865 285854 | Thomas.Smith2@dpag.ox.ac.uk
>
> ________________________________________
> From: Andreas Heger [notifications@github.com]
> Sent: 09 April 2015 15:02
> To: CGATOxford/cgat
> Cc: Thomas Smith
> Subject: Re: [cgat] Ts counts2counts rewrite (#168)
>
> I currently get:
>
> FAIL: tests/wig2wig.py/version
>
> Traceback (most recent call last):
> File
> "/ifs/apps/apps/python-2.7.9/lib/python2.7/site-packages/nose/case.py",
> line 197, in runTest
> self.test(*self.arg)
> File "/ifs/devel/andreas/cgat/tests/test_scripts.py", line 178, in
> check_script
> ok_(not fail, msg)
> AssertionError: files /tmp/tmppkwjCb/stdout and
> tests/counts2counts.py/normed_million_counts.tsv are not the same
> /bin/bash -c 'gunzip <
>  >
> /tmp/tmppkwjCb/stdout'
> md5: output=98c680e35384aed2583e1f8febf891b0
> reference=fd829ea8837198bb3cf05f0b7a1044f7
>
> FAIL: tests/wig2wig.py/version
>
> Traceback (most recent call last):
> File
> "/ifs/apps/apps/python-2.7.9/lib/python2.7/site-packages/nose/case.py",
> line 197, in runTest
> self.test(*self.arg)
> File "/ifs/devel/andreas/cgat/tests/test_scripts.py", line 178, in
> check_script
> ok_(not fail, msg)
> AssertionError: files /tmp/tmpG6WEb3/stdout and
> tests/counts2counts.py/normed_deseq_size_factors.tsv are not the same
> /bin/bash -c 'gunzip <
> /ifs/devel/andreas/cgat/tests/counts2counts.py/counts_small.tsv.gz |
> python /ifs/devel/andreas/cgat/scripts/counts2counts.py
> --method=normalize --normalization-method=deseq-size-factors -v 0 >
> /tmp/tmpG6WEb3/stdout'
> md5: output=5f8c2b519309ec396f54f09676b8e75f
> reference=5ce593b804317479158011874472f192
>
> Best wishes,
> Andreas
>
> �
> Reply to this email directly or view it on
> GitHub<https://github.com/CGATOxford/cgat/pull/168#issuecomment-91241387>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CGATOxford/cgat/pull/168#issuecomment-91242897>.
>

**Comment by TomSmithCGAT** [comment]
Umm, that is odd. I've run the commands and saved the output in /ifs/devel/toms/testing_area/a.out & b.out. The tests pass when I use these files as references.


________________________________

**Comment by AndreasHeger** [comment]
The point is that mine are different, and indeed, see:

/ifs/devel/andreas/cgat/b.out

Best wishes,
Andreas

**Comment by AndreasHeger** [comment]
For future reference, it seems the difference might have been due to two 
different python versions (2.7.1 vs 2.7.9)

**Comment by TomSmithCGAT** [comment]
Reference files for tests re-created with python 2.7.9

**Comment by AndreasHeger** [comment]
Thanks! Merged and closed.

**Pull request merged**
