### PR TITLE
Fix for UnicodeEncodeError in CSV2DB

### PR DESCRIPTION
**Pull request by AntonioJBT**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Many thanks @AntonioJBT !

**Comment by sebastian-luna-valero** [comment]
Hi @AntonioJBT 

cc @Acribbs 

We are having a problem with this change, and the `csv2db.py` script is not working properly with the following code:

```
cat example.txt | cgat csv2db --retry --database-backend=sqlite --database-name=csvdb --table=gene_info
```

where `example.txt` is:
```
gene_id	exon_version	gene_biotype	gene_name	gene_source	gene_version	havana_gene	havana_gene_version	havana_transcript	havana_transcript_version	tag	transcript_biotype	transcript_source	transcript_support_level	transcript_version
ENSG00000223972		transcribed_unprocessed_pseudogene	DDX11L1	havana	5	OTTHUMG00000000961	2	OTTHUMT00000362751	1	basic	processed_transcript	havana	1	2
ENSG00000223972	1	transcribed_unprocessed_pseudogene	DDX11L1	havana	5	OTTHUMG00000000961	2	OTTHUMT00000362751	1	basic	processed_transcript	havana	1	2
```

With the code change on this pull request we get an empty `csvdb` table as output. If I revert the change to the previous version, `csv2db.py` works again and the `csvdb` table is populated as expected.

Before reverting this on the master branch, could you please give us an example where the original code was not working for you? 

Best regards,
Sebastian

**Comment by AntonioJBT** [comment]
Hi Sebastian and @Acribbs,
Apologies. I pulled the trigger without testing properly. I get the error when executing from a pipeline:

.. block:

    UnicodeEncodeError: 'utf-8' codec can't encode character '\udce2' in position 0: surrogates not allowed

I haven't had a chance to test properly but the pipeline_quickstart.py template calls this and might reproduce it.

The fix I sent however also gives an empty database. It looks like we could use a test for this?
I'll try to test later or tomorrow though for the error above.
I suggest you revert in the meantime...
Sorry...!
Best,
Antonio

**Comment by sebastian-luna-valero** [comment]
Thanks @AntonioJBT 

Reverting change and adding test in https://github.com/CGATOxford/cgat/pull/360

Regarding your error, I suggest you try the `--utf8` option of `csv2db.py` and if that doesn't work, please try prefixing the script with `LANG=en_GB.UTF-8`; i.e. `LANG=en_GB.UTF-8 cgat csv2db <your-arguments-here>` (we found a similar issue with some Python 3 code on our environment that was solved with this last option)

Please let us know whether that works for you.

Best regards,
Sebastian

**Pull request merged**
