### PR TITLE
Mm gwas scripts

### PR DESCRIPTION
**Pull request by MikeDMorgan**
This is the first set of scripts utilised in the GWAS pipeline.  They all act as standalone scripts, making use of the common `PipelineGWAS` module file (name to change to `GWAS` to reflect more general purpose).
Unit tests are implemented for the following scripts:
assoc2assoc.py
assoc2coloc.py
assoc2plot.py
geno2assoc.py

Further test for the remaining scripts will follow:
geno2geno.py
geno2qc.py
pheno2pheno.py
pheno2plot.py
qcs2qc.py
snpPriority.py
snps2architecture.py
testPleiotropy.py

### CODE REVIEW

**Comment by MikeDMorgan** [comment]
@sebastian-luna-valero Several tests are failing based on the absence of two R libraries: __coloc__ and __ggplot2__.  Can these be included in the Travis build?

**Comment by sebastian-luna-valero** [comment]
Thanks @MikeDMorgan 

Will do. I am troubleshooting a conda issue:
https://github.com/bioconda/bioconda-recipes/issues/3496

**Comment by MikeDMorgan** [comment]
Thank Sebastian, I saw the build was failing to execute properly on the active CGATPipelines pull requests.

**Comment by sebastian-luna-valero** [comment]
Hi Mike,

I have now added `coloc` and `ggplot2`. I think I only need to add `qqman`, is that right?
https://travis-ci.org/CGATOxford/cgat/jobs/192140363

Please have a look at the other errors. It looks like this one:
https://travis-ci.org/CGATOxford/cgat/jobs/192140369

is related to the way that dictionaries are accessed in Python 3.

Finally, is `snpPriority` a script that you are adding your self?
https://travis-ci.org/CGATOxford/cgat/jobs/192140370

Best regards,
Sebastian

**Comment by MikeDMorgan** [comment]
Hi Sebastian,
Sorry, I thought `qqman` was already in the R build.

**Comment by sebastian-luna-valero** [comment]
Thanks, Mike.

Waiting for tests to pass:
https://travis-ci.org/bioconda/bioconda-recipes/builds/193449256

**Comment by MikeDMorgan** [comment]
Some Travis tests are failing due to a difference in rounding between the Travis build and my local environment. https://travis-ci.org/CGATOxford/cgat/jobs/193490920

Additional test failures are due to an inability to use the X-server for graphical plotting (calling PNG device specifically).

**Comment by MikeDMorgan** [comment]
@sebastian-luna-valero @AndreasHeger is the R scripts directory included in the Travis build?

**Comment by sebastian-luna-valero** [comment]
@MikeDMorgan this is the content of your branch:
https://github.com/CGATOxford/cgat/tree/MM_gwas_scripts

Travis clones it into the testing environment before running any tests. What do you think is exactly the problem?

**Comment by MikeDMorgan** [comment]
Currently the tests for assoc2coloc.py require the explicit passing of the path to the location of the R scripts dir.  This is passed as `../../R/` to the script as a command-line option.  The relative path cannot find the `R/` directory, despite this relative path being correct from either `CGAT/scripts/` or `tests/assoc2coloc.py`.

**Comment by MikeDMorgan** [comment]
Travis condo-build uses pandas 19.2, whilst the local/CGT version of pandas is 18.1 on Python 2.7.11.  This appears to be the cause of an error with the number of reported decimal places is different.

PNG device initialisation (i.e. X11) fails on Travis, is this a general issue with Travis, or would it be better to remove unit tests for images?

**Comment by sebastian-luna-valero** [comment]
Thanks, Mike.

Now trying `xvfb` as instructed in the docs:
https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

to check whether that solves your issues with PNG device initialisation.

**Comment by sebastian-luna-valero** [comment]
The PNG device initialisation problem seems to have gone after enabling `xvfb` on Travis.

Regarding the location of `Rscript`, would it be possible to use the output of `which Rscript`? That should make it more portable, I think.

Regarding the different floating point representation between Python 2 and 3, should you create separate tests for each case? See the `skip_python` option here:
https://github.com/CGATOxford/cgat/blob/master/tests/randomize_lines.py/tests.yaml

**Comment by MikeDMorgan** [comment]
Sorry, it's not `Rscript` itself that is passed, it's the location of the CGAT R/ directory, where a specific block of R code is sourced from.

**Comment by MikeDMorgan** [comment]
Merge GWAS scripts into main repository.  Some script documentation still requires expanding/finishing.  I'll create a new branch once the Python 3 migration is complete

**Pull request merged**
