### PR TITLE
Code changes to work with pysam 0.13.0

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
@AndreasHeger @Acribbs please review

### CODE REVIEW

**Comment by Acribbs** [comment]
Have also updated the test for bam2bam nh-flag.bam because the test output was the same when using samtools view but the binary was different. We copied the new test output and replaced it with the old one.

**Comment by Acribbs** [comment]
hmm iv seen this error before, I will look into it tomorrow.

**Comment by Acribbs** [comment]
So I have ran

```
zcat geneset.dir/refcoding.gtf.gz     | grep ENST00000459772
```

and it seems for this gene there is no p_id being generated during the cufflinks step for this gene. It may require more investigation as to why because it isn't clear to me at the moment what the exact problem is.

**Comment by Acribbs** [comment]
have ran:

```
zcat Homo_sapiens.GRCh38.87.gtf.gz     | cat     | grep "transcript_id"     | cgat gtf2gtf     --method=sort --sort-order=gene+transcript     | grep ENST00000373020

```

and the transcript has exon id that other transcripts for this gene dont have. Will look into this further.

**Comment by sebastian-luna-valero** [comment]
Hi,

Following up our discussion over the group meeting today, I just wanted to confirm that the version of `cufflinks` in our central installation and the conda environment is the same (2.2.1), so this should not be the cause of the problem.

Best regards,
Sebastian

**Comment by Acribbs** [comment]
gtf2tsv: p_id issue: This seems to be relatated to a python 3.6 issue because on my py35 environment I can run the script no problem on the commandline.

**Comment by Acribbs** [comment]
Ah I see what the issue is now, it should have been obvious when an `AttributeError` is raised (i.e. the value is not present in the attributes column) the val is not set to " " but raises a KeyError not an `AttributeError`. Not sure why AttributeError has changed from python 3.5 to KeyError in py 3.6. I think the fix is to capture both exceptions. Where would you like me to make the fix? @sebastian-luna-valero In a seperate cgat branch?

**Pull request merged**
