### PR TITLE
new method rename-chr

### PR DESCRIPTION
**Pull request by kevinrue**
I needed to bring some BED files from mm10 to GRCm38 chromosomes.

### CODE REVIEW

**Comment by kevinrue** [comment]
Oops: I accidentally submitted the PR with a Shift+Return keyboard shortcut before I finished writing my comment. So here is the rest:
This PR implements a new method that takes a two-column TAB delimited file that maps source chromosome names to target names. See https://github.com/dpryan79/ChromosomeMappings for examples.
This avoids issues where a simple trimming of 'chr' does not work (e.g. `chrM` -> `MT`)
I couldn't find a utility to do this anywhere else.
I hope that's useful. Let me know if this is relevant for a PR, and if more documentation is required.

**Comment by sebastian-luna-valero** [comment]
Many thanks @kevinrue 

Would it be possible to add a test for this new method?
https://github.com/CGATOxford/cgat/tree/master/tests/bed2bed.py

Please let me know if you need help with the testing.

**Comment by kevinrue** [comment]
I've actually started doing the same for gff2gff, as I'm facing the same issue with other input files.
I can look at tests for both of them simultaneously when I'm done with the second one. I'll give you a shout if I struggle.
Best,
Kevin

**Comment by sebastian-luna-valero** [comment]
Great, many thanks!

**Pull request merged**
