### PR TITLE
Implimeted lfcshrink function for new deseq2

### PR DESCRIPTION
**Pull request by Acribbs**
Testing on the ran-seq pipeline passes

### CODE REVIEW

**Comment by Acribbs** [comment]
@sebastian-luna-valero Just pushed new code for testing

**Comment by Acribbs** [comment]
@sebastian-luna-valero have made change and it is ready to test.

**Comment by Acribbs** [comment]
@sebastian-luna-valero Newer changes to plotMA

**Comment by sebastian-luna-valero** [comment]
thanks @Acribbs 

testing now.

**Comment by sebastian-luna-valero** [comment]
As discussed, closed in favour of #371

**Pull request closed without merging**
