### PR TITLE
bam_vs_bed.py: work on stream. sorting optional, default=off.

### PR DESCRIPTION
**Pull request by snsansom**
This script appears somewhat flawed in purpose/design - really rewriting it as (i) a more generic script that computes summary statistics on the output of intersectBed or (ii) to use pybedtools might be better.

Here, in order to avoid the use of temporary files the script now calls itself in the bash statement that it constructs - a bit ugly, but far friendly on disk usage and much faster that writing and reading a temporary file. Probably preferable to creating a second script to just do the counting. An alternative would be to use a gnarly awk statement to summarise the counts.

Please note that sorting is now optional and off by default.

### CODE REVIEW

**Comment by snsansom** [comment]
Andreas - I'm fairly sure that removing the iterator and counting line-by-line gives the same results (tested on a paired end bam file). Also I'm wondering if this is the correct way to be counting overlaps for paired end files - I think intersectBed is handling it but I'm not sure...

**Comment by AndreasHeger** [comment]
Thanks, @snsansom . Can I have a go? I was thinking more of using
subprocess.popen to do the pipe processing.

Best wishes,
Andreas

**Comment by snsansom** [comment]
Sure! Really I'm wondering if this script shouldn't just expect an
intersectBed stream as input rather than running intersectBed itself...

Best wishes,
Steve

**Comment by AndreasHeger** [comment]
I have just pushed a change, let me know what you think. I prefer to keep the call to intersectBed in the script. This way the dependency is well encapsulated.
Best,
Andreas

**Comment by snsansom** [comment]
Looks, good to me (I checked memory usage and output). The only difference
is that the script can't be used simply as a counter (I'm still not quite
convinced that CGAT scripts should wrap other tools in this way but that's
a philosophical point!) - please pull this and I'll delete the branch.

Thanks,
Steve

**Pull request merged**
