### PR TITLE
Gtf2gtf retained introns

### PR DESCRIPTION
**Pull request by IanSudbery**
I've added a new method to gtf2gtf.py for identifying retained introns. I've defined retained introns as an intron within one transcript that is entirely contained within the exon of another. 

To be honest, I don't know if gtf2gtf is the right place for this method. The obvious format to output retained introns in is bed, but it fit better with the other gene-model manipulation type methods in gtf2gtf than in gff2bed. Open to suggestions for a better home. 

More implementation details in the documentation:

```python-docstring
``find-retained-introns``
 Finds intervals within a transcript that represent retained-introns,
 here a retained intron is considered to be an intron in one transcript
 that is entirely contianed within the exon of another. The retained
 intron will be assigned to the transcript with the containing exon. Where
 multiple, overlapping introns are contained within a single exon of a
 transcript, the union of the introns will be output. Thus when considering
 an indevidual transcript, outputs will be non-overlapping. However,
 overlapping, or even identical feature can be output if they belong to
 different transcripts.
```

Its fast (the complete transcriptome finishes in 22 seconds) and I've included a test.

### CODE REVIEW

**Comment by IanSudbery** [comment]
@sebastian-luna-valero This appears to be failing the Travis build because the build is stalling, rather than because there are any test fails. Is there any way I can try to rerun the tests? Or should I go ahead and merge without?

**Comment by sebastian-luna-valero** [comment]
@IanSudbery 

I have seen these errors happening before and it is normally safe to merge as the build is stalled due to problems on their end.

However, it is possible to restart a build on Travis as explained here:
http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

I have already done so for your PR, so let's wait for the result before merging:
https://travis-ci.org/CGATOxford/cgat/builds/48934382

Best regards,
Sebastian.

**Comment by IanSudbery** [comment]
@AndreasHeger Any views on whether gtf2gtf is the right place for this?

**Comment by AndreasHeger** [comment]
@IanSudbery , many thanks for this. Both gtf2gtf and gtf2gff would be good places for this.
gtf2gff transforms a "geneset" to a list of "features" and retained introns could be regarded as genomic features. However, gtf2gtf is fine as well (gene set transformation) as you might want to keep the transcript/gene information intact after processing.

**Pull request merged**
